version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  test:
    build: .
    command: sh -c "npm test --detectOpenHandles --reporters=default --reporters=jest-junit"
    links:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    depends_on:
      - db
      - app