version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    command: ["node", "index.js"]
    depends_on:
      - db
    networks:
      - albums-app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 30s
      retries: 30
    networks:
      - albums-app-network

  # Ajoutez le réseau aux autres services de la même manière...

networks:
  albums-app-network:
    external: true