version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    command: ["node", "index.js"]
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 30s
      retries: 30

  test:
    build: .
    command: sh -c "npm install && npm install --save-dev jest-junit && npm test --detectOpenHandles --reporters=default --reporters=jest-junit"
    links:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    depends_on:
      - db
      - app

  cypress:
    image: "cypress/browsers:node14.17.0-chrome88-ff89"
    depends_on:
      - app
      - db
    volumes:
      - ./:/e2e
    working_dir: /e2e
    command: /bin/bash -c "export CYPRESS_SERVER_URL=http://app:3000 && cypress verify && npx cypress run"

  eslint:
    build: .
    command: npm run lint
    volumes:
      - .:/app
      
networks:
  albums-app-network:
    external: true


