version: '3'
services:
  # Service pour l'application principale
  app:
    # Construit le service à partir du Dockerfile dans le répertoire courant
    build: .
    # Expose le port 8080 du service
    ports:
      - "8080:8080"
    # Lie ce service au service de base de données 'db'
    links:
      - db
    # Définit une variable d'environnement pour la connexion à la base de données
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque

  # Service pour la base de données
  db:
    # Utilise l'image Docker 'mongo:latest' pour ce service
    image: mongo:latest
    # Expose le port 27017 du service
    ports:
      - "27017:27017"

  # Service pour exécuter les tests
  test:
    # Construit le service à partir du Dockerfile dans le répertoire courant
    build: .
    # Exécute une série de commandes pour installer les dépendances et exécuter les tests
    command: sh -c "npm install && npm install --save-dev jest-junit && npm test -- --reporters=default --reporters=jest-junit"
    # Lie ce service au service de base de données 'db'
    links:
      - db
    # Définit une variable d'environnement pour la connexion à la base de données
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
    # Montage de volumes pour le code de l'application et les résultats des tests
    volumes:
      - .:/app
      - ./test-results:/app/test-results