version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://db:27017/phototheque
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  cypress:
    build: .
    command: /bin/bash -c "cypress verify && npx cypress run"
    links:
      - db
    volumes:
      - ./:/e2e
    working_dir: /e2e
    depends_on:
      - db
      - app
    environment:
      - CYPRESS_SERVER_URL=http://app:3000
    
  eslint:
    build: .
    command: sh -c "npm run lint"
    volumes:
      - .:/app
    working_dir: /app