version: '3'

services:
  app:
    image: node_project-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://db:27017/mydatabase
    depends_on:
      - db

  db:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 30s
      retries: 30
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: